### ISSUE TITLE
Pushing events in client

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-events#14]
Client can only listen, and not add events. Fix ASAP.

**Comment by elmigranto** [comment]
Question poped up about our "channel masks". Since we are setting `clientId` to `pkg.api`, it would make sense to use that as channel prefix. Say we are `service/v1` and send event of type `banana`. From what I understand, those should end up in 2 channels: `service/v1` and `service/v1:banana`.

Options:
  - make user of client lib manually send to 2 channels;
  - inside client lib post 2 events with same data (one for each channel);
  - server would create 2 evnets based on `clientId` and `event.type`;
  - same as above, unless `channel` explicitly specified.

**Comment by elmigranto** [comment]
First one seems least surprising to me, but it somewhat defeats a point of listening on `service/v1`. Other options sound like narrowing `ganomede-events` and what channel means within it (message of kind X from service Y, not some arbirtray channel id).

**Comment by j3k0** [comment]
Why do "publishers" send their clientID (which I believe is used to track what's the last _received_ event for a client) ?

Let's forget about events mask and stay simple. Client specify the channel he wants to publish to, message goes to this channel.

**Comment by elmigranto** [comment]
`clientId`:
  - `GET` when worker wakes up, it doesn't know last message id it received, but server does;
  - `POST` wasn't discussed, but I added it there too, `channel` part still comes from `body.channel`.

Would make sense to use `clientId:even-type` as channel when sending messages, since I don't think `users/v1` would post stuff to `invitations/v2`. Guess it all depends on what we actually going to post and how we are going to listen for those things. If all we want is `users/v1:new-user` (and similar), let's make client to do that explicitly, and server duplicate that to `users/v1`.

Well, then we have different IDs for essentially the same message. I guess we should drop masks idea all together.

So for now:

  - channel must be explicitly passed in to `client.send` — if you want to post to 2 channels, do 2 requests;
  - server posts exactly where it was asked to, no duplication;
  - `clientId` basically ignored for `send` (meaning client won't try to derive channel from that).

**Comment by j3k0** [comment]
Great, I'd rather have this module stay generic.

We can imagine "users/v1" post stuff to channels serving other purposes, like "system-errors", "facebook-events", "database-updates", or whatever.

**Comment by elmigranto** [comment]
Don't close yet, it still uses clientId + event for channel…

**Comment by elmigranto** [comment]
Close in #15
