### ISSUE TITLE
handle req_id in Client.send (eventArg)

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-events#21]
eventArg might contain a `req_id` field.

This should be added as the `x-request-id` header in the outgoing POST request.

**Comment by elmigranto** [comment]
I assume we want to leave `req_id` in event?

**Comment by j3k0** [comment]
Yes `req_id` in the event can be useful: then workers like mailchimp can reuse it in outgoing requests. This thing helps a lot with traceability.
